namespace MineImatorSimplyRemade;

public class Enums
{
    public enum Platform
    {
        Windows,
        MacOS,
        Linux
    }
    
    public enum Project
    {
        Format1 = 1,
        Format2 = 2,
        Format5 = 3,
        Format6 = 4,
        Format7Demo = 5,
        Format100Demo2 = 6,
        Format100Demo3 = 7,
        Format100Demo4 = 8,
        Format100Debug = 9,
        Format100 = 10,
        Format105 = 11,
        Format105Q2 = 12,
        Format106 = 13,
        Format106Q2 = 14,
        FormatCb100 = 20,
        FormatCb100Pre = 21,
        FormatCb102 = 22,
        FormatCb103 = 23,
        Format110Pre1 = 24,
        Format110Pre3 = 25,
        Format110 = 26,
        Format113 = 27,
        Format120Pre1 = 28,
        Format120Pre3 = 29,
        Format122 = 30,
        Format123Pre2 = 31,
        Format125 = 32,
        Format200Pre1 = 33,
        Format200Pre5 = 34,
    }

    public enum Settings
    {
        Format100Demo4 = 0,
        Format100Demo5 = 1,
        Format100 = 2,
        Format103 = 3,
        Format106 = 4,
        Format106Q2 = 5,
        Format106Q3 = 6,
        FormatCb100 = 20,
        FormatCb102 = 22,
        FormatCe110 = 23,
        Format110Pre1 = 24,
        Format110 = 25,
        Format113 = 26,
        Format114 = 27,
        Format120 = 28,
        Format200 = 29,
    }

    public enum MinecraftAssets
    {
        Format110Pre1 = 1,
        Format110Pre2 = 2,
        Format113 = 3,
        Format120 = 4,
        Format123 = 5,
        Format128 = 6,
        Format129 = 7,
        Format200 = 8,
        Format201 = 9,
    }
    
    public enum MinecraftPack
    {
        Format161 = 1,
        Format19 = 2,
        Format111 = 3,
        Format113 = 4,
        Format115 = 5,
        
        Latest = 5
    }

    public enum ValueType
    {
        Transform,
        TransformPos,
        TransformRot,
        TransformScale,
        TransformBend,
        TransformPathPoint,
        
        Material,
        MaterialTexture,
        MaterialColor,
        MaterialSurface,
        MaterialSubsurface,
        
        Particles,
        Light,
        Spotlight,
        Camera,
        Background,
        Sound,
        Text,
        Keyframe,
        RotPoint,
        Hierarchy,
        Appearance,
        Audio,
        Item,
        Path,
        
        Amount
    }

    public enum Value
    {
        PosX,
        PosY,
        PosZ,
        RotX,
        RotY,
        RotZ,
        ScaleX,
        ScaleY,
        ScaleZ,
        BendLegacy,
        BendX,
        BendY,
        BendZ,
        Alpha,
        RgbAdd,
        RgbSub,
        RgbMul,
        HsbAdd,
        HsbSub,
        HsbMul,
        MixColor,
        GlowColor,
        MixPercent,
        Emissive,
        Metallic,
        Roughness,
        Subsurface,
        SubsurfaceRadiusRed,
        SubsurfaceRadiusGreen,
        SubsurfaceRadiusBlue,
        SubsurfaceColor,
        WindInfluence,
        Spawn,
        Freeze,
        Clear,
        CustomSeed,
        Seed,
        Attractor,
        Force,
        ForceDirectional,
        ForceVortex,
        LightColor,
        LightStrength,
        LightSpecularStrength,
        LightSize,
        LightRange,
        LightFadeSize,
        LightSpotRadius,
        LightSpotSharpness,
        CamFov,
        CamBladeAmount,
        CamBladeAngle,
        CamLightManagement,
        CamTonemapper,
        CamExposure,
        CamGamma,
        CamRotate,
        CamRotateDistance,
        CamRotateAngleXy,
        CamRotateAngleZ,
        CamShake,
        CamShakeMode,
        CamShakeStrengthX,
        CamShakeStrengthY,
        CamShakeStrengthZ,
        CamShakeSpeedX,
        CamShakeSpeedY,
        CamShakeSpeedZ,
        CamDof,
        CamDofDepth,
        CamDofRange,
        CamDofFadeSize,
        CamDofBlurSize,
        CamDofBlurRatio,
        CamDofBias,
        CamDofThreshold,
        CamDofGain,
        CamDofFringe,
        CamDofFringeAngleRed,
        CamDofFringeAngleGreen,
        CamDofFringeAngleBlue,
        CamDofFringeRed,
        CamDofFringeGreen,
        CamDofFringeBlue,
        CamBloom,
        CamBloomThreshold,
        CamBloomIntensity,
        CamBloomRadius,
        CamBloomRatio,
        CamBloomBlend,
        CamLensDirt,
        CamLensDirtBloom,
        CamLensDirtGlow,
        CamLensDirtRadius,
        CamLensDirtIntensity,
        CamLensDirtPower,
        CamColorCorrection,
        CamContrast,
        CamBrightness,
        CamSaturation,
        CamVibrance,
        CamColorBurn,
        CamGrain,
        CamGrainStrength,
        CamGrainSaturation,
        CamGrainSize,
        CamVignette,
        CamVignetteRadius,
        CamVignetteSoftness,
        CamVignetteStrength,
        CamVignetteColor,
        CamCa,
        CamCaBlurAmount,
        CamCaDistortChannels,
        CamCaRedOffset,
        CamCaGreenOffset,
        CamCaBlueOffset,
        CamDistort,
        CamDistortRepeat,
        CamDistortZoomAmount,
        CamSizeUseProject,
        CamSizeKeepAspectRatio,
        CamWidth,
        CamHeight,
        BgImageShow,
        BgImageRotation,
        BgSkyMoonPhase,
        BgSkyTime,
        BgSkyRotation,
        BgSunlightStrength,
        BgSunlightAngle,
        BgSkySunAngle,
        BgSkySunScale,
        BgSkyMoonAngle,
        BgSkyMoonScale,
        BgTwilight,
        BgSkyCloudsShow,
        BgSkyCloudsSpeed,
        BgSkyCloudsHeight,
        BgSkyCloudsOffset,
        BgGroundShow,
        BgGroundSlot,
        BgBiome,
        BgSkyColor,
        BgSkyCloudsColor,
        BgSunlightColor,
        BgAmbientColor,
        BgNightColor,
        BgGrassColor,
        BgFoliageColor,
        BgWaterColor,
        BgLeavesOakColor,
        BgLeavesSpruceColor,
        BgLeavesBirchColor,
        BgLeavesJungleColor,
        BgLeavesAcaciaColor,
        BgLeavesDarkOakColor,
        BgLeavesMangroveColor,
        BgFogShow,
        BgFogSky,
        BgFogCustomColor,
        BgFogColor,
        BgFogCustomObjectColor,
        BgFogObjectColor,
        BgFogDistance,
        BgFogSize,
        BgFogHeight,
        BgWind,
        BgWindSpeed,
        BgWindStrength,
        BgWindDirection,
        BgWindDirectionalSpeed,
        BgWindDirectionalStrength,
        BgTextureAnimationSpeed,
        TextureObject,
        TextureMaterialObject,
        TextureNormalObject,
        SoundObject,
        SoundVolume,
        SoundPitch,
        SoundStart,
        SoundEnd,
        Text,
        TextFont,
        TextHAlign,
        TextVAlign,
        TextAntialiasing,
        TextOutline,
        TextOutlineColor,
        CustomItemSlot,
        ItemSlot,
        ItemName,
        PathObject,
        PathOffset,
        PathPointAngle,
        PathPointScale,
        IkTarget,
        IkBlend,
        IkTargetAngle,
        IkAngleOffset,
        Visible,
        Transition,
        EaseInX,
        EaseInY,
        EaseOutX,
        EaseOutY,
        
        Amount
    }
    
    public enum TemplateType
    {
        Character,
        SpecialBlock,
        Scenery,
        Item,
        Block,
        BodyPart,
        ParticleSpawner,
        Text,
        Cube,
        Cone,
        Cylinder,
        Sphere,
        Surface,
        Model
    }
    
    public enum TimelineType
    {
        Character,
        SpecialBlock,
        Scenery,
        Item,
        Block,
        BodyPart,
        ParticleSpawner,
        Text,
        Cube,
        Cone,
        Cylinder,
        Sphere,
        Surface,
        Model,
        Camera,
        Spotlight,
        Pointlight,
        Folder,
        Background,
        Audio,
        Path,
        PathPoint,
        
        LightSource,
        Shape,
        
        Amount
    }
    
    public enum ResourceType
    {
        Pack,
        PackUnzipped,
        Skin,
        DownloadedSkin,
        ItemSheet,
        LegacyBlockSheet,
        BlockSheet,
        Scenery,
        FromWorld,
        ParticleSheet,
        Texture,
        Font,
        Sound,
        Model
    }
    
    public enum ShapeType
    {
        Cube,
        Cone,
        Cylinder,
        Sphere,
        Surface,
        
        Amount
    }
    
    public enum ModelFormat
    {
        MineImatorModel,
        Block
    }
    
    public enum Icons
    {
        AlignBottom,
        AlignLeft,
        AlignMiddle,
        AlignCenter,
        AlignRight,
        AlignTop,
        Announcement,
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        Asset,
        AssetAdd,
        AssetExport,
        AssetImport,
        AssetInstance,
        AssetList,
        AwardsRecent,
        Back,
        Beaker,
        Bell,
        BellSlash,
        Bend,
        BendSharp,
        Beta,
        Birthday,
        Block,
        BlockSpecial,
        Bold,
        BoundaryBox,
        BoundaryCircle,
        BoundaryCube,
        BoxSelect,
        Broom,
        Brush,
        BrushSmall,
        Bug,
        Calendar,
        Camera,
        CameraPhoto,
        CameraPhotoSmall,
        Cards,
        Character,
        CharacterParts,
        CheckboxIndeterminate,
        CheckboxTick,
        ChevronDown,
        ChevronDownTiny,
        ChevronLeft,
        ChevronLeftTiny,
        ChevronRight,
        ChevronRightTiny,
        ChevronUp,
        ChevronUpTiny,
        Circle,
        CircleOutline,
        Clapperboard,
        ClapperboardSmall,
        ClearFormat,
        ClickLeft,
        ClickMiddle,
        ClickRight,
        Clock,
        Close,
        CloseSmall,
        Cloud,
        Code,
        Comment,
        Comments,
        Compact,
        Cone,
        ConeDark,
        Content,
        Copy,
        CopyAll,
        CopyKeyframe,
        CopySmall,
        Crown,
        Cube,
        CubeDark,
        CubeAdd,
        Customization,
        Cut,
        CutAll,
        CutKeyframe,
        Cylinder,
        CylinderDark,
        Dashboard,
        Delete,
        DeleteKeyframe,
        DeleteSelection,
        Discord,
        Donate,
        Dot,
        Download,
        DragLeft,
        DragMiddle,
        DragRight,
        Dragger,
        Duplicate,
        DuplicateSelection,
        Dusk,
        EaseBack,
        EaseBounce,
        EaseCircular,
        EaseCubic,
        EaseCustom,
        EaseElastic,
        EaseExponential,
        EaseIn,
        EaseInOut,
        EaseInstant,
        EaseLinear,
        EaseOut,
        EaseQuad,
        EaseQuart,
        EaseQuint,
        EaseSine,
        EllipsisHorizontal,
        EllipsisVertical,
        Emoji,
        Envelope,
        Exit,
        External,
        File,
        FileAdd,
        FileExport,
        FileImport,
        FileObject,
        FileSmall,
        FileTemplate,
        Filter,
        Fire,
        Fireworks,
        Flag,
        Folder,
        FolderAdd,
        FolderEdit,
        FolderImport,
        FolderRecents,
        Followed,
        FollowedSettings,
        ForumStats,
        Forward,
        FrameNext,
        FramePrevious,
        Ghost,
        GhostSmall,
        Grid,
        Group,
        Heart,
        HeartBroken,
        Help,
        HelpCircle,
        Hidden,
        HiddenSmall,
        Hierarchy,
        HierarchySmall,
        Highlighter,
        Historian,
        Home,
        Ignore,
        Image,
        ImageExport,
        Info,
        Internal,
        Italics,
        Item,
        ItemSmall,
        Joint,
        JointSmall,
        Key,
        Keyboard,
        KeyboardSmall,
        Keyframe,
        KeyframeFilled,
        KeyframeFilledSmall,
        KeyframeNext,
        KeyframePrevious,
        KeyframeSmall,
        Laptop,
        Letterbox,
        Library,
        LibrarySmall,
        LightOmni,
        LightPoint,
        LightPointSmall,
        LightSpot,
        Lightbulb,
        Link,
        LinkRemove,
        LinkSmall,
        ListBulletedLtr,
        ListBulletedRtl,
        ListBulletedSmall,
        ListNumberedLtr,
        ListNumberedRtl,
        Lock,
        LockSmall,
        Logout,
        Lounge,
        Magnet,
        Manual,
        Mark,
        Marker,
        MarkerAdd,
        Maximize,
        Medal,
        Menu,
        Merge,
        Minimize,
        MirrorHorizontally,
        MirrorVertically,
        Mobile,
        Model,
        Moon,
        Move,
        Movie,
        MovieExport,
        MultiTransform,
        Mute,
        MuteSmall,
        Newspaper,
        Note,
        NoteSmall,
        Overlays,
        Palette,
        Part,
        PartAdd,
        PartImport,
        Particles,
        ParticlesSmall,
        Paste,
        PasteAll,
        PasteFormat,
        PasteKeyframe,
        PasteSmall,
        Path,
        PathPoint,
        PathSmall,
        Pause,
        Pencil,
        Person,
        PersonAdd,
        PersonClose,
        PersonEdit,
        PersonOutline,
        PersonRecent,
        PersonSettings,
        PersonStats,
        PersonTick,
        Phi,
        Picker,
        PickerSmall,
        PillarBox,
        Pin,
        PinSmall,
        Pivot,
        Plane,
        Plane3D,
        Plane3DDark,
        PlaneAdd,
        Play,
        PlayRegion,
        Plus,
        Poll,
        Posing,
        PostRecents,
        ProgramSettings,
        Quality,
        Puppetry,
        Quote,
        Randomize,
        Recents,
        RecentsRemove,
        Redo,
        Refresh,
        Reload,
        Rename,
        Repeat,
        RepeatSeamless,
        Replace,
        Reply,
        Reset,
        ResetAll,
        ResetSmall,
        RocketShip,
        Rotate,
        Rotate180,
        RotateCCW,
        RotateCW,
        RunCycle,
        Save,
        SaveAs,
        SaveKeyframe,
        Scale,
        Scenery,
        Scroll,
        Search,
        Select,
        SelectAll,
        SelectAllKeyframe,
        Send,
        Settings,
        SettingsExport,
        SettingsImport,
        SettingsSetDefault,
        SettingsSmall,
        Shapes,
        Share,
        Shield,
        Sliders,
        SortDown,
        SortUp,
        Sphere,
        SphereDark,
        SphereFlat,
        SphereMaterial,
        SphereMaterialDark,
        SphereMaterialSmall,
        SphereMaterialSmallDark,
        SphereShading,
        SphereShadingDark,
        SphereShadingSmall,
        SphereShadingSmallDark,
        SphereTexture,
        SplitCorner,
        SplitHorizontal,
        SplitVertical,
        Star,
        Stop,
        Stopwatch,
        Strikethrough,
        Sun,
        Tag,
        TagAdd,
        TagRemove,
        Text,
        TextAlignCenter,
        TextAlignLeft,
        TextAlignRight,
        TextColor,
        TextSmall,
        Texture,
        TextureExport,
        Tick,
        Topic,
        Transform,
        TransformSmall,
        TransformationGimbal,
        TransformationGlobal,
        TransformationLocal,
        Trophy,
        Tutorials,
        Twitter,
        Underline,
        Undo,
        Unlock,
        UnlockSmall,
        Unmark,
        Unread,
        Vcard,
        ViewGrid,
        ViewList,
        ViewportSecondary,
        Visible,
        VisibleSmall,
        Volume,
        VolumeSmall,
        Walk,
        WalkCycle,
        Wand,
        WarningCircle,
        WarningDiamond,
        WarningTriangle,
        Wave,
        Web,
        Wind,
        Workbench,
        World,
        WorldSmall,
        Youtube
    }
    
    public enum RenderMode
    {
        Click,
        Select,
        Place,
        Preview,
        Color,
        ColorFog,
        ColorFogLights,
        AlphaFix,
        AlphaTest,
        Depth,
        DepthNoSky,
        HighLightSunDepth,
        HighLightSpotDepth,
        HighLightPointDepth,
        HighLightSun,
        HighLightSpot,
        HighLightPoint,
        HighLightPointShadowless,
        HighFog,
        ColorGlow,
        SceneTest,
        HighDepthNormal,
        AoMask,
        Material,
        Subsurface,
        Glint
    }
    
    public enum ViewMode
    {
        Flat,
        Shaded,
        Render
    }
    
    public enum Menu
    {
        List,
        ListSeamless,
        Timeline,
        Biome,
        TransitionList,
        Content
    }

    public enum Buttons
    {
        Primary,
        Secondary,
        Tertiary,
        Toolbar,
        Big,
        
        NoText,
        Text,
        Caption,
        Label
    }

    public enum InputBox
    {
        Left,
        Right,
        Big
    }
    
    public enum Anchor
    {
        Left,
        Center,
        Right,
    }
    
    public enum Option
    {
        Browse = -10,
        ImportWorld = -11,
        DownloadSkin = -12,
        DownloadSkinDone = -13,
        ImportItemSheet = -14
    }

    public enum Direction
    {
        East,
        West,
        South,
        North,
        Up,
        Down,
        
        Amount
    }
    
    public enum Part
    {
        Right,
        Left,
        Front,
        Back,
        Upper,
        Lower,
        
        Amount
    }
    
    public enum Bend
    {
        Forward,
        Backward,
        Both
    }

    public enum Scrollbar
    {
        Vertical,
        Horizontal,
    }
    
    public enum BlockDepth
    {
        Depth0, //Opaque
        Depth1, //Transparent
        Depth2, //Semi-transparent
        
        Amount
    }
    
    public enum BlockVBuffer
    {
        Normal,
        Animated,
        Grass,
        Foliage,
        LeavesOak,
        LeavesSpruce,
        LeavesBirch,
        LeavesJungle,
        LeavesAcacia,
        LeavesDarkOak,
        LeavesMangrove,
        Water,
        
        Amount
    }
    
    public enum VertexWave
    {
        None,
        ZOnly,
        All
    }
    
    public enum NBT
    {
        TagEnd = 0,
        TagByte = 1,
        TagShort = 2,
        TagInt = 3,
        TagLong = 4,
        TagFloat = 5,
        TagDouble = 6,
        TagByteArray = 7,
        TagString = 8,
        TagList = 9,
        TagCompound = 10,
        TagIntArray = 11,
        TagLongArray = 12,
        
        Amount
    }
    
    public enum Toast
    {
        Info,
        Positive,
        Warning,
        Negative
    }
    
    public enum ViewTool
    {
        Select,
        Move,
        Rotate,
        Scale,
        Bend,
        Transform,
        
        Amount
    }
    
    public enum ViewControl
    {
        PosX,
        PosY,
        PosZ,
        PosXY,
        PosXZ,
        PosYZ,
        PosPan,
        
        RotX,
        RotY,
        RotZ,
        
        ScaleX,
        ScaleY,
        ScaleZ,
        ScaleXY,
        ScaleXZ,
        ScaleYZ,
        ScaleXYZ,
        
        BendX,
        BendY,
        BendZ,
        
        RotAngleXy,
        RotAngleZ,
        RotDistance
    }
    
    public enum Mouse
    {
        ClickLeft,
        ClickMiddle,
        ClickRight,
        DragLeft,
        DragMiddle,
        DragRight,
        Scroll
    }

    public enum RenderPass
    {
        Combined,
        Diffuse,
        Specular,
        Ao,
        Shadows,
        Indirect,
        IndirectShadows,
        Reflections,
        DepthU24,
        Normal,
        Material,
        
        Amount
    }
    
    public enum RaytracingType
    {
        Reflections,
        Indirect,
        ShadowsDirectional
    }

    public enum Material
    {
        FormatNone,
        FormatSEUS,
        FormatLabPBR
    }

    public enum Glint
    {
        None,
        Item,
        Entity
    }
    
    public enum AlphaMode
    {
        Blend,
        Hashed,
        Default
    }

    public enum ToneMapper
    {
        None,
        Reinhard,
        ACES
    }
    
    public enum Window
    {
        Main,
        ViewSecond,
        Timeline
    }
}